const fs=require('fs'),assert=require('assert');
const runtime=fs.readFileSync('app/src/main/assets/game/endless-chaos-runtime.js','utf8');
const gradle=fs.readFileSync('app/build.gradle','utf8');
assert(runtime.includes('DUAL_TRIGGER_V30'),'v30 runtime id missing');
for(const fn of ['triggerLayout','triggerModeAt','drawTriggerButton','drawFocusShot','drawBurstShot','focusImpact','burstImpact','energyArc','emitGameEvent','liveSnapshot','applyDirectorCommand'])assert(runtime.includes('function '+fn),fn+' missing');
assert(runtime.includes('FOCUS')&&runtime.includes('CRYSTAL ARC'),'focus trigger missing');
assert(runtime.includes('BURST')&&runtime.includes('PULSE WAVE'),'burst trigger missing');
assert(runtime.includes('activePointers:new Map()'),'dual trigger must support independent/multi-touch pointers');
assert(runtime.includes('e.shotCount*(cp.double?2:1)'),'v28 weapon evolution must remain shared across both triggers');
assert(runtime.includes('mode==="BURST"?"BURST":"FOCUS"'),'weapon mode routing missing');
assert(runtime.includes('kind:mode'),'shot style must travel with each projectile');
assert(runtime.includes('shape==="shard"'),'crystal impact shards missing');
assert(runtime.includes('drawEnergyArcs'),'new curved energy arc renderer missing');
assert(runtime.includes('crew:game-event'),'Gemini Live event bridge missing');
assert(runtime.includes('play_pulse')&&runtime.includes('1400'),'Live bridge must batch taps instead of streaming every tap');
assert(runtime.includes('stage_start')&&runtime.includes('quiet_moment')&&runtime.includes('soft_landing'),'semantic Live events missing');
assert(runtime.includes('window.DualTriggerV30'),'v30 API missing');
assert(/versionCode\s+408/.test(gradle),'v30 versionCode missing');
assert(/0\.59\.0-dual-trigger-v30/.test(gradle),'v30 versionName missing');
console.log('dual-trigger-v30.test.js PASS');
