const fs=require('fs');
const assert=require('assert');
const legacy=fs.readFileSync('app/src/main/assets/game/excitement-layer-v30-2.js','utf8');
const tapRush=fs.readFileSync('app/src/main/assets/game/tap-rush-v30-4.js','utf8');
const pureBeam=fs.readFileSync('app/src/main/assets/game/pure-beam-v30-6.js','utf8');
const index=fs.readFileSync('app/src/main/assets/game/index.html','utf8');
const gradle=fs.readFileSync('app/build.gradle','utf8');

assert(legacy.includes('EXCITEMENT_PET_V30_2'),'v30.2 compatibility marker missing');
assert.doesNotThrow(()=>new Function(legacy),'legacy excitement layer has invalid JS syntax');
assert.doesNotThrow(()=>new Function(tapRush),'tap rush controller has invalid JS syntax');
assert.doesNotThrow(()=>new Function(pureBeam),'pure beam controller has invalid JS syntax');
const active=index.includes('pure-beam-v30-6.js')?'pure-beam-v30-6.js':'tap-rush-v30-4.js';
assert(index.includes(active),'replacement excitement controller not loaded');
assert(index.indexOf(active)<index.indexOf('endless-chaos-runtime.js'),'active excitement controller must load before heavy dual-trigger runtime');
for(const name of ['NEEDLE','PRISM','COMET','STAR_CUT','ORB','RING','BUBBLE','NOVA'])assert(tapRush.includes(name),`legacy shot variant ${name} missing`);
assert(tapRush.includes('hype_level'),'legacy HYPE milestone event missing');
assert(tapRush.includes('surge_start'),'legacy SURGE event missing');
assert(tapRush.includes('pet_assist'),'legacy pet assist event missing');
assert(pureBeam.includes('beam_tier'),'v30.6 beam-tier excitement event missing');
assert(pureBeam.includes('beam_surge'),'v30.6 beam surge event missing');
assert(pureBeam.includes('intensity_reset'),'v30.6 reset event missing');
assert(pureBeam.includes('window.ExcitementPetV302'),'public v30.2 compatibility API missing');
assert(gradle.includes('// v30.2 marker versionCode 409'),'v30.2 version marker missing');
console.log('excitement-pet-v30-2.test.js PASS');
