const fs=require('fs'),assert=require('assert');
const g=fs.readFileSync('app/src/main/assets/game/game.js','utf8');
const p=fs.readFileSync('app/src/main/assets/game/promise-runtime.js','utf8');
const fx=fs.readFileSync('app/src/main/assets/game/world-fx-controller.js','utf8');
assert(g.includes('promise:null'),'tap state must have a dedicated visual promise runtime');
assert(g.includes('handlePromisePhase')&&g.includes('handlePromiseReveal'),'FOMO must have escalation and reveal beats');
assert(p.includes('nextTease:!!this.next'),'the next mystery must be seeded before payoff completes');
assert(p.includes('betrayalUntil'),'promise chain needs a false-calm/betrayal beat');
assert(p.includes('this.current.progress=Math.max(.90'),'false calm must return close to reveal instead of resetting');
assert(fx.includes('tapPromiseAccent('),'world FX should punctuate promise escalation');
assert(fx.includes('tapJackpot('),'world FX should punctuate promise payoff');
for(const text of ['KEEP GOING','ONE MORE?','SO CLOSE.'])assert(!g.includes(text),'FOMO must not rely on instructional text');
assert(!g.includes('Math.floor((state.taps-1)/4)%8'),'must not restore the old fixed phase machine');
console.log('fomo-loop.test.js PASS');
