const fs=require('fs'),assert=require('assert');
const index=fs.readFileSync('app/src/main/assets/game/index.html','utf8');
const game=fs.readFileSync('app/src/main/assets/game/game.js','utf8');
const runtime=fs.readFileSync('app/src/main/assets/game/experience-runtime.js','utf8');
const gemini=fs.readFileSync('app/src/main/java/com/magic76/aiclicker/GeminiLiveClient.java','utf8');
assert(index.indexOf('promise-runtime.js')>index.indexOf('world-mutation-runtime.js'),'PromiseRuntime should build on persistent world mutation');
assert(index.indexOf('promise-runtime.js')<index.indexOf('experience-runtime.js'),'PromiseRuntime must load before ExperienceRuntime');
assert.strictEqual((game.match(/new PromiseRuntime\(/g)||[]).length,1,'there must be exactly one PromiseRuntime');
assert(game.includes('state.promise.tap(px,py'),'every physical tap must advance the unresolved visual');
assert(game.includes('state.promise.steer(plan)'),'AI plans may bias the next visual mystery without owning it');
assert(game.includes('handlePromiseReveal'),'promise reveal must have a bounded payoff path');
assert(game.includes('state.runtime.forceLocalPromiseConsequence'),'a reveal must cause a local gameplay consequence, not just a flash');
assert(game.includes('state.mutation.jackpot(e.x,e.y,level)'),'promise payoff must feed the persistent world instead of resetting it');
assert(game.includes('state.promise.targetModulation(nowT)'),'unresolved mystery must affect the primary target body');
assert(runtime.includes('promiseContext'),'ExperienceRuntime must expose local promise state as context');
assert(runtime.includes('forceLocalPromiseConsequence(meta)'),'promise gameplay changes must still flow through the sole ExperienceRuntime owner');
for(const consequence of ['RIFT:{situation:"CHASE"','ECHO:{situation:"DECOY"','SHADOW:{situation:"MIRROR"','FALSE_CALM:{situation:"FAKE_ENDING"'])assert(runtime.includes(consequence),'missing reveal consequence '+consequence);
assert(runtime.includes('ctx.visualPromise=this.promiseContext()||null'),'Gemini context must include unresolved visual state');
assert(gemini.includes('DIRECTIVE.context.visualPromise'),'Gemini prompt must understand PromiseRuntime as local truth');
for(const banned of ['KEEP GOING','ONE MORE?','SO CLOSE.','WHAT ELSE?'])assert(!game.includes(banned),'visible text FOMO must be removed: '+banned);
assert(!game.includes('nextFomoGoal'),'old hidden tap-goal loop must be retired');
console.log('promise-integration.test.js PASS');
