const fs=require('fs');
const path=require('path');
const root=path.join(__dirname,'..');
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const dir=read('app/src/main/assets/game/signature-moment-director.js');
const runtime=read('app/src/main/assets/game/signature-moment-runtime.js');
const exp=read('app/src/main/assets/game/experience-runtime.js');
const schema=read('app/src/main/java/com/magic76/aiclicker/GeminiWorldToolSchema.java');
if(/return\s*["']SCREEN_SHATTER/.test(dir))throw new Error('director can still choose SCREEN_SHATTER');
if(!runtime.includes('if(key==="SCREEN_SHATTER")return false'))throw new Error('runtime does not hard-block SCREEN_SHATTER');
if(!exp.includes('safeRaw.signatureMoment="NONE"'))throw new Error('stale AI SCREEN_SHATTER is not normalized away');
if(schema.includes('"FLASHLIGHT_HUNT","SCREEN_SHATTER"'))throw new Error('Gemini schema still exposes SCREEN_SHATTER');
console.log('screen-shatter-disabled.test.js PASS');
