const fs=require('fs'),assert=require('assert');
const game=fs.readFileSync('app/src/main/assets/game/game.js','utf8');
const art=fs.readFileSync('app/src/main/assets/game/production-asset-art.js','utf8');
const gradle=fs.readFileSync('app/build.gradle','utf8');
assert(game.includes('WORLD_MAP_VISIBILITY_V21')||game.includes('OBJECT_POLISH_WORLD_V22')||game.includes('TAP_VARIETY_V23')||game.includes('ACTION_BUTTON_V24'),'v21+ renderer id missing');
assert((game.match(/start:true/g)||[]).length===10,'all 10 cast members should start active');
assert(game.includes('bgWorldCurrent.alpha=1'),'world background should be fully visible');
assert(game.includes('activePets().length'),'active pet diagnostics missing');
assert(art.includes('new Image()'),'v21 art loader should use manual image loading');
assert(art.includes('status(){')||art.includes('function status()'),'v21 art diagnostics missing');
assert(/versionCode\s+(399|400|401|402)/.test(gradle)&&(/0\.50\.0-world-visibility-v21/.test(gradle)||/0\.51\.0-object-polish-v22|0\.52\.0-tap-variety-v23|0\.53\.0-action-button-v24/.test(gradle)),'v21+ gradle version missing');
console.log('world-visibility-v21.test.js PASS');
