const fs=require('fs'),assert=require('assert');
const index=fs.readFileSync('app/src/main/assets/game/index.html','utf8');
const game=fs.readFileSync('app/src/main/assets/game/game.js','utf8');
const runtime=fs.readFileSync('app/src/main/assets/game/experience-runtime.js','utf8');
const fx=fs.readFileSync('app/src/main/assets/game/world-fx-controller.js','utf8');
const mutation=fs.readFileSync('app/src/main/assets/game/world-mutation-runtime.js','utf8');
const gemini=fs.readFileSync('app/src/main/java/com/magic76/aiclicker/GeminiLiveClient.java','utf8');
assert(index.indexOf('world-mutation-runtime.js')<index.indexOf('experience-runtime.js'),'mutation runtime must load before ExperienceRuntime');
assert.strictEqual((game.match(/new WorldMutationRuntime\(/g)||[]).length,1,'there must be exactly one persistent mutation runtime');
assert(game.includes('state.mutation.tap(px,py'),'every physical tap must push world pressure');
assert(game.includes('state.mutation.promise(Math.min(4,e.phaseIndex),e.x,e.y)'),'visual promise phase beats must reinforce the same world pressure');
assert(game.includes('state.mutation.jackpot(e.x,e.y,level)'),'promise reveal payoff must feed persistent world evolution');
assert(game.includes('state.mutation.setWorld(plan.world)'),'validated world plan must synchronize mutation visuals');
assert(game.includes('targetModulation(nowT)'),'target body must visually reflect world pressure');
assert(fx.includes('mutationStageAccent('),'stage crossings need pooled visual punctuation');
assert(runtime.includes('rupturesUntilWorldShift'),'AI/fallback world switching must respect mutation lifespan');
assert(runtime.includes('this.director.startSession(previousWorld)'),'director internal state must be restored when an early world switch is blocked');
assert(runtime.includes('forceLocalWorldMutation(meta)'),'world shift must still flow through ExperienceRuntime');
assert(runtime.includes('this.allowWorldShiftOnce=true'),'only a mutation epoch may unlock a local world shift');
assert(gemini.includes('DIRECTIVE.context.worldMutation'),'Gemini must receive mutation state as creative context');
const tapBody=mutation.slice(mutation.indexOf('tap(x,y,meta)'),mutation.indexOf('promise(stage,x,y)'));
assert(!tapBody.includes('new global.PIXI'),'tap critical path must not allocate Pixi display objects');
assert(mutation.includes('20fps background animation'),'complex persistent background should be throttled below 60fps');
assert(!game.includes('Math.floor((state.taps-1)/4)%8'),'old fixed tap phases must remain absent');
console.log('world-mutation-integration.test.js PASS');
