const fs=require('fs'),assert=require('assert');
const game=fs.readFileSync('app/src/main/assets/game/game.js','utf8');
const art=fs.readFileSync('app/src/main/assets/game/production-asset-art.js','utf8');
const pets=fs.readFileSync('app/src/main/assets/game/sprite-pet-runtime.js','utf8');
const gradle=fs.readFileSync('app/build.gradle','utf8');
assert(game.includes('PRODUCTION_ART_WORLD_V19')||game.includes('WORLD_RULES_CAST_V20'),'v19+ world renderer lineage missing');
assert(game.includes('cast-sheet-10.png'),'v19 should use the 10-character cast sheet');
assert((game.match(/atlasIndex:/g)||[]).length===10,'v19 should define 10 atlas characters');
assert(game.includes('WORLD_ROTATION')&&game.includes('worldCharge')&&game.includes('setWorld(0,{immediate:true})'),'v19 world rotation system missing');
assert(art.includes('CANDY_TOY_ROOM')&&art.includes('CRYSTAL_SKY_GARDEN')&&art.includes('UNDERWATER_BUBBLE_PALACE')&&art.includes('STARLIGHT_CARNIVAL'),'v19 world art paths missing');
assert(pets.includes('SpritePetAtlasGrid')&&pets.includes('ATLAS_DEFAULT={columns:5,rows:2}')&&pets.includes('ATLAS_FRAME_COUNT=8'),'v19 atlas runtime missing');
assert(/versionCode\s+(397|398|399|400)/.test(gradle),'v19+ gradle version missing');
console.log('world-cast-v19.test.js PASS');
